#ifndef SCENE_CONFIGURATIONS_H
#define SCENE_CONFIGURATIONS_H

#define SCENE_TOP_Y_PADDING 6
#define SCENE_TITLE_ELEMENT_HEIGHT 5
#define SCENE_TITLE_ELEMENT_Y_PADDING 4
#define SCENE_SCENE_ELEMENT_Y_PADDING 3

typedef enum {
    START_SCENE,
    COMMAND_SCENE,
    HELP_SCENE,
    INSERT_SCENE,
    SEARCH_SCENE,
    REMOVE_SCENE,
    TOTAL_SCENES
} SceneID;

#endif