#ifndef SCENE_ELEMENT_CONFIGURATIONS_H
#define SCENE_ELEMENT_CONFIGURATIONS_H

#define SCENE_ELEMENT_TEXT_LENGTH 32
#define SCENE_ELEMENT_HEIGHT 3
#define SCENE_ELEMENT_TEXT_X_PADDING 4
#define SCENE_ELEMENT_INPUT_TEXT_LENGTH 64

typedef enum {
    TEXT_LABEL_SCENE_ELEMENT,
    TEXT_BUTTON_SCENE_ELEMENT,
    TEXT_INPUT_SCENE_ELEMENT
} SceneElementID;

#endif